tailwind.config = {
    theme: {
      extend: {
        fontFamily: {
          robotoMono: ['"Roboto Mono"', "monospace"],
        },
        backgroundImage: {
          "blue-gradiente":
            "linear-gradient(to right, #007BFF -120%, #024FA3 -50%, #040404 135%)",
          "background-blue": "url('../../assets/background-blue.svg')",
          "background-purple": "url('../../assets/background-purple.svg')",
          profile: "url('../../assets/profile.jpg')",
          instagramSvg: "url('../../assets/instagramSvg.svg')",
          linkedinSvg: "url('../../assets/linkedinSvg.svg')",
          githubSvg: "url('../../assets/githubSvg.svg')",
          bookmarkSvg: "url('../../assets/bookmarkSvg.svg')",
          briefcaseSvg: "url('../../assets/briefcaseSvg.svg')",
          filetextSvg: "url('../../assets/filetextSvg.svg')",
          infoSvg: "url('../../assets/infoSvg.svg')",
          layersSvg: "url('../../assets/layersSvg.svg')",
          downloadSvg: "url('../../assets/downloadSvg.svg')",
          globeSvg: "url('../../assets/globeSvg.svg')",
          programmingSvg: "url('../../assets/programmingSvg.svg')",
          angularSvg: "url('../../assets/angularSvg.svg')",
          figmaSvg: "url('../../assets/figmaSvg.svg')",
          gitSvg: "url('../../assets/gitSvg.svg')",
          htmlCssJsSvg: "url('../../assets/htmlCssJsSvg.svg')",
          javaSvg: "url('../../assets/javaSvg.svg')",
          mysqlSvg: "url('../../assets/mysqlSvg.svg')",
          postgresqlSvg: "url('../../assets/postgresqlSvg.svg')",
          reactSvg: "url('../../assets/reactSvg.svg')",
          springSvg: "url('../../assets/springSvg.svg')",
          tailwindcssSvg: "url('../../assets/tailwindcssSvg.svg')",
          typescriptSvg: "url('../../assets/typescriptSvg.svg')",
          diplomaSvg: "url('../../assets/diplomaSvg.svg')",
          certificateSvg: "url('../../assets/certificateSvg.svg')",
          clipboardSvg: "url('../../assets/clipboardSvg.svg')",
          arrowupSvg: "url('../../assets/arrowupSvg.svg')",
          justifySvg: "url('../../assets/justifySvg.svg')",
          closeSvg: "url('../../assets/closeSvg.svg')",
        },
        colors: {
          projectBlue: "#003ADF",
          projectBlack: "#1C1C1C",
          projectGray: "#424242",
        },
      },
    },
  };